import Head from "next/head";
import Image from "next/image";
import { useAuth } from "../lib/auth";
import styles from "../styles/Home.module.css";

export default function Home() {
  const auth = useAuth();
  console.log(auth);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {auth.user ? (
          <h1 className={styles.title}>
            <a href="#">{auth.user.email}</a>
          </h1>
        ) : (
          <button onClick={(e) => auth.signin()}>Signin</button>
        )}
      </main>
    </div>
  );
}
